/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easyderby.view;

import easyderby.Funciones;
import java.awt.event.KeyEvent;

/**
 *
 * @author Omar
 */
public class agregarPartido extends javax.swing.JDialog {

    /**
     * Creates new form agregarPartido
     */
    String partido[] = null;
    Funciones f;
    public agregarPartido(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtPartido.requestFocus();
        f = new Funciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPartido = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPartidos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Partido:");

        txtPartido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPartido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPartidoKeyPressed(evt);
            }
        });

        tblPartidos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblPartidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPartidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblPartidosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblPartidos);
        if (tblPartidos.getColumnModel().getColumnCount() > 0) {
            tblPartidos.getColumnModel().getColumn(0).setResizable(false);
            tblPartidos.getColumnModel().getColumn(0).setPreferredWidth(1);
            tblPartidos.getColumnModel().getColumn(1).setResizable(false);
        }

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easyderby/img/checkmark-30.png"))); // NOI18N
        jButton1.setText("Aceptar");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easyderby/img/cancel-30.png"))); // NOI18N
        jButton2.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPartido))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPartidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPartidoKeyPressed

         if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            setVisible(false);            
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String filtro = txtPartido.getText();
            f.actualizarTabla(tblPartidos, f.buscarPartido(filtro));
        } else {
            if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_ENTER) {
                tblPartidos.requestFocus();
                tblPartidos.setRowSelectionInterval(0, 0);
            } else {
                char ch = evt.getKeyText(evt.getKeyCode()).toLowerCase().charAt(0);
                if ((ch >= 97 && ch <= 122) || (ch >= 48 && ch <= 57)) {
                    String filtro = txtPartido.getText() + ch;
                    System.out.println(filtro);
                    f.actualizarTabla(tblPartidos, f.buscarPartido(filtro));
                }
            }

        }
      
    }//GEN-LAST:event_txtPartidoKeyPressed

    private void tblPartidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblPartidosKeyPressed
      if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            setVisible(false);
            
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (tblPartidos.getSelectedRow() != -1) {
                int id = Integer.parseInt(tblPartidos.getValueAt(tblPartidos.getSelectedRow(), 0).toString());
                partido = f.getPartidoDetalle(id);
               
                setVisible(false);
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "No has seleccionado", "ERROR", 0);
            }
        }
  
  
    }//GEN-LAST:event_tblPartidosKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPartidos;
    private javax.swing.JTextField txtPartido;
    // End of variables declaration//GEN-END:variables
}
