/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easyderby.view;

import easyderby.Conexion;
import easyderby.Funciones;
import java.awt.Desktop;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.JRPdfExporter;

/**
 *
 * @author Omar
 */
public class Reportes extends javax.swing.JDialog {

    /**
     * Creates new form Reportes
     */
    Funciones f;
    int idTorneo=-1;
    public Reportes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        f = new Funciones();
        ArrayList<String[]> torneos = f.getTorneosActivos();
        cmbTorneos.removeAllItems();
        cmbTorneos.addItem("Selecciona...");
        for (int i = 0; i < torneos.size(); i++) {
           cmbTorneos.addItem(torneos.get(i)[0].toString()+". "+torneos.get(i)[1].toString());    
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnPeleas = new org.edisoncor.gui.button.ButtonPopup();
        btnCotejo = new org.edisoncor.gui.button.ButtonPopup();
        btnPeleasComplete = new org.edisoncor.gui.button.ButtonPopup();
        cmbTorneos = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Torneo:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reportes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        btnPeleas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easyderby/img/pdf_2-30.png"))); // NOI18N
        btnPeleas.setText("Peleas");
        btnPeleas.setEnabled(false);
        btnPeleas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeleasActionPerformed(evt);
            }
        });

        btnCotejo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easyderby/img/pdf_2-30.png"))); // NOI18N
        btnCotejo.setText("Puntajes");
        btnCotejo.setEnabled(false);
        btnCotejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCotejoActionPerformed(evt);
            }
        });

        btnPeleasComplete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easyderby/img/pdf_2-30.png"))); // NOI18N
        btnPeleasComplete.setText("Peleas completo");
        btnPeleasComplete.setEnabled(false);
        btnPeleasComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeleasCompleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPeleasComplete, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(btnCotejo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPeleas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPeleas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCotejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPeleasComplete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        cmbTorneos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTorneos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTorneosActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easyderby/img/hand_cursor-30.png"))); // NOI18N
        jButton1.setText("Consultar...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTorneos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTorneos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPeleasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeleasActionPerformed

        JasperReport jasperReport;
        JasperPrint jasperPrint;
        Conexion conexion = new Conexion();
        try {

            jasperReport = JasperCompileManager.compileReport("Peleas.jrxml");
            Map parametros = new HashMap();
            parametros.put("idTorneo", "" + idTorneo);
            System.out.println("ID: " + idTorneo);
            jasperPrint = JasperFillManager.fillReport(jasperReport, parametros, conexion.conn);
            JRExporter ex = new JRPdfExporter();
            ex.setParameter(JRExporterParameter.JASPER_PRINT, jasperPrint);
            ex.setParameter(JRExporterParameter.OUTPUT_FILE, new java.io.File("peleas.pdf"));
            ex.exportReport();
            File path = new File("peleas.pdf");
            Desktop.getDesktop().open(path);
        } catch (Exception ex) {
            ex.printStackTrace();

        }
    }//GEN-LAST:event_btnPeleasActionPerformed

    private void btnCotejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCotejoActionPerformed
        JasperReport jasperReport;
        JasperPrint jasperPrint;
        Conexion conexion = new Conexion();
        try {

            jasperReport = JasperCompileManager.compileReport("cotejo.jrxml");
            Map parametros = new HashMap();
            parametros.put("idTorneo", "" + idTorneo);
            jasperPrint = JasperFillManager.fillReport(jasperReport, parametros, conexion.conn);
            JRExporter ex = new JRPdfExporter();
            ex.setParameter(JRExporterParameter.JASPER_PRINT, jasperPrint);
            ex.setParameter(JRExporterParameter.OUTPUT_FILE, new java.io.File("cotejo.pdf"));
            ex.exportReport();
            File path = new File("cotejo.pdf");
            Desktop.getDesktop().open(path);
        } catch (Exception ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_btnCotejoActionPerformed

    private void btnPeleasCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeleasCompleteActionPerformed
        JasperReport jasperReport;
        JasperPrint jasperPrint;
        Conexion conexion = new Conexion();
        try {

            jasperReport = JasperCompileManager.compileReport("DetallePeleas.jrxml");
            Map parametros = new HashMap();
            parametros.put("idTorneo", "" + idTorneo);
            jasperPrint = JasperFillManager.fillReport(jasperReport, parametros, conexion.conn);
            JRExporter ex = new JRPdfExporter();
            ex.setParameter(JRExporterParameter.JASPER_PRINT, jasperPrint);
            ex.setParameter(JRExporterParameter.OUTPUT_FILE, new java.io.File("DetallePeleas.pdf"));
            ex.exportReport();
            File path = new File("DetallePeleas.pdf");
            Desktop.getDesktop().open(path);
        } catch (Exception ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_btnPeleasCompleteActionPerformed

    private void cmbTorneosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTorneosActionPerformed
        
    }//GEN-LAST:event_cmbTorneosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        idTorneo = Integer.parseInt(cmbTorneos.getSelectedItem().toString().split("\\.")[0]);
        System.out.println("ID: "+idTorneo);
        btnCotejo.setEnabled(true);
        btnPeleas.setEnabled(true);
        btnPeleasComplete.setEnabled(true);

    }//GEN-LAST:event_jButton1ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonPopup btnCotejo;
    private org.edisoncor.gui.button.ButtonPopup btnPeleas;
    private org.edisoncor.gui.button.ButtonPopup btnPeleasComplete;
    private javax.swing.JComboBox<String> cmbTorneos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
